version: "3.1"

services:
  nginx:


  postgres:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  mongo:
    image: mongo:2.4.11
    restart: always
    env_file:
      - .env.mongo
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "16379:6379"

  web_app:
    build:
      context: ./kiary-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - kiary-web-app/.env.local
    depends_on:
      - mongo