name: kiary msa test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Get code from repository
        uses: actions/checkout@v3

      - name: Use Node.js lts
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: '**/node_modules'
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: npm ci --only=production

      - name: Build project
        run: npm run build

      - name: Run test:ci
        run: npm run test
